### PR TITLE
Added Heroku Time Left To Status Bar

### PR DESCRIPTION
**Pull request by kalanakt**
- added, how much time is left in Heroku dyno and disable web page preview in genlink.py

### CODE REVIEW

**Comment by subinps** [comment]
Not everyone will be using heroku.
And move that codes from heroku.py to utils.py

**Comment by kalanakt** [comment]
now fine?

**Comment by subinps** [comment]
> now fine?

No, You messed up the  code :(

**Comment by kalanakt** [comment]
where 👀😪
but telegram bot works as I wish

https://telegra.ph/file/c4ded20977758989724ab.jpg
https://telegra.ph/file/e6383149e689419da946d.jpg

Since other Deploy methods have nothing to do with app.json, adding `Time left` does not affect other Deploy methods?

**Pull request closed without merging**
