### PR TITLE
Missed feature🤐

### PR DESCRIPTION
**Pull request by athul1706**

### CODE REVIEW

**Comment by subinps** [comment]
What you mean?
I can't find anything here.
Explain what featur you mean?

**Comment by athul1706** [comment]
> What you mean? I can't find anything here. Explain what featur you mean?

>It's not kinda feature.. It's something Tessa have.when clicking on someone's results.Its shows Thats not for you.

**Comment by shamilhabeebnelli** [comment]
its not a logical matter, just some patti show specs, bye

**Comment by subinps** [comment]
Its useless to have that.
Anyone can use the existing buttons but no one can change the page except the one who requested the movie

**Comment by athul1706** [comment]
> Its useless to have that. Anyone can use the existing buttons but no one can change the page except the one who requested the movie

>Yeah but thats in media search.Here nobody can use the existing buttons too except the one who requested.I thought that was useful in groups to increase count in messages..Anyway if this is useless leave it😬

**Pull request closed without merging**
